### ISSUE TITLE
Duplicate blog title in blog view

### ISSUE THREAD

**Issue by chetanvarshney** [ewinslow/elgg-facebook_theme#75]
Hi Evan please fix duplicate blog title in blog view.

For example http://elgg.ektasoftwares.com/blog/view/136/this-is-text-blog-title

Thanks

**Comment by anzumdigital** [comment]
Hi,
We have duplicate button and breadcrumbs being loaded on the members section of the site. Screenshots attached. It goes on all the similar pages.
What is the best possible solution. The resolved bug for duplicate entries still seems to prevail on this installation.

![screenshot_33](https://cloud.githubusercontent.com/assets/6666546/5734152/65bdaa94-9bd5-11e4-9e95-7a5ec94138fe.png)
![screenshot_34](https://cloud.githubusercontent.com/assets/6666546/5734153/65c7a300-9bd5-11e4-9f55-97f880359cf2.png)

Thanks
Marshall

**Comment by ewinslow** [comment]
This plugin is not supported.
